services:
  - type: web
    name: whisper-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python whisper.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PORT
        value: 8080 